FROM python:3.10-slim

WORKDIR /usr/app

RUN pip install --no-cache-dir \
    streamlit==1.28.2 \
    pandas==2.0.3 \
    numpy==1.24.3 \
    plotly==5.17.0 \
    psycopg2-binary==2.9.9 \
    scikit-learn==1.3.2 \
    altair==5.1.2 \
    pillow==10.1.0

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]